src/Entity/Stagiair.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StagiairRepository")
 */
class Stagiair
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\User", cascade={"persist", "remove"})
     */
    private $User_id;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $urentotaal;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $begindatum;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $einddatum;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $school;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contactpersoon;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contactpersoon_email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $contactpersoon_telefoonnr;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $urenperdag;

    public function __construct()
    {
        /* Zorgt dat in /new de huidige datum en tijd wordeb weergeven */

        $this->begindatum = new \DateTime();
        $this->einddatum = new \DateTime();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->User_id;
    }

    public function setUserId(?User $User_id): self
    {
        $this->User_id = $User_id;

        return $this;
    }

    public function getUrentotaal(): ?float
    {
        return $this->urentotaal;
    }

    public function setUrentotaal(?float $urentotaal): self
    {
        $this->urentotaal = $urentotaal;

        return $this;
    }

    public function getBegindatum(): ?\DateTimeInterface
    {
        return $this->begindatum;
    }

    public function setBegindatum(?\DateTimeInterface $begindatum): self
    {
        $this->begindatum = $begindatum;

        return $this;
    }

    public function getEinddatum(): ?\DateTimeInterface
    {
        return $this->einddatum;
    }

    public function setEinddatum(?\DateTimeInterface $einddatum): self
    {
        $this->einddatum = $einddatum;

        return $this;
    }

    public function getSchool(): ?string
    {
        return $this->school;
    }

    public function setSchool(?string $school): self
    {
        $this->school = $school;

        return $this;
    }

    public function getContactpersoon(): ?string
    {
        return $this->contactpersoon;
    }

    public function setContactpersoon(?string $contactpersoon): self
    {
        $this->contactpersoon = $contactpersoon;

        return $this;
    }

    public function getContactpersoonEmail(): ?string
    {
        return $this->contactpersoon_email;
    }

    public function setContactpersoonEmail(?string $contactpersoon_email): self
    {
        $this->contactpersoon_email = $contactpersoon_email;

        return $this;
    }

    public function getContactpersoonTelefoonnr(): ?string
    {
        return $this->contactpersoon_telefoonnr;
    }

    public function setContactpersoonTelefoonnr(?string $contactpersoon_telefoonnr): self
    {
        $this->contactpersoon_telefoonnr = $contactpersoon_telefoonnr;

        return $this;
    }

    public function getUrenperdag()
    {
        return $this->urenperdag;
    }

    public function setUrenperdag($urenperdag): self
    {
        $this->urenperdag = $urenperdag;

        return $this;
    }

    public function __toString()
    {
        return (string)$this->User_id;
    }
}

src/Form/StagiairType.php
<?php

namespace App\Form;

use App\Entity\Stagiair;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StagiairType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('urentotaal', null, ['label' => 'Aantal uren'])
            ->add('urenperdag')
            ->add('begindatum')
            ->add('einddatum')
            ->add('school')
            ->add('contactpersoon')
            ->add('contactpersoon_email', null, ['label' => 'Emailadres Contactpersoon'])
            ->add('contactpersoon_telefoonnr', null, ['label' => 'Telefoonnummer Contactpersoon'])
            ->add('User_id', null, ['label' => 'User'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stagiair::class,
        ]);
    }
}

src/Controller/StagiairController.php
<?php

namespace App\Controller;

use App\Entity\Stagiair;
use App\Form\StagiairType;
use App\Repository\StagiairRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/stagiair")
 */
class StagiairController extends AbstractController
{
    /**
     * @Route("/", name="stagiair_index", methods={"GET"})
     */
    public function index(StagiairRepository $stagiairRepository): Response
    {

        if ($this->isGranted("ROLE_SUPER_ADMIN")){

            return $this->render('stagiair/index.html.twig', ['stagiairs' => $stagiairRepository->findAll()]);
        } else {

            return $this->render('stagiair/index.html.twig', [
                'stagiairs' => $stagiairRepository->findBy(
                    [
                        'User_id' => $this->getUser()
                    ]
                ),
            ]);
        }
    }

    /**
     * @Route("/new", name="stagiair_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $stagiair = new Stagiair();
        $form = $this->createForm(StagiairType::class, $stagiair);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($stagiair);
            $entityManager->flush();

            return $this->redirectToRoute('stagiair_index');
        }

        return $this->render('stagiair/new.html.twig', [
            'stagiair' => $stagiair,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="stagiair_show", methods={"GET"})
     */
    public function show(Stagiair $stagiair): Response
    {
        return $this->render('stagiair/show.html.twig', [
            'stagiair' => $stagiair,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="stagiair_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Stagiair $stagiair): Response
    {
        $form = $this->createForm(StagiairType::class, $stagiair);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('stagiair_index', [
                'id' => $stagiair->getId(),
            ]);
        }

        return $this->render('stagiair/edit.html.twig', [
            'stagiair' => $stagiair,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="stagiair_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Stagiair $stagiair): Response
    {
        if ($this->isCsrfTokenValid('delete'.$stagiair->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($stagiair);
            $entityManager->flush();
        }

        return $this->redirectToRoute('stagiair_index');
    }
}

templates/stagiair/_delete_form.html.twig
<form method="post" action="{{ path('stagiair_delete', {'id': stagiair.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stagiair.id) }}">
    <button class="btn btn-danger mt-5"><i class="fas fa-trash-alt"></i></button>
</form>

templates/stagiair/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success greenbutton float-right"><i class="fas fa-save"></i></button>
{{ form_end(form) }}

templates/stagiair/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Stagiair{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header maincolor whitetext">
        Edit Stagiair    </div>

    <div class="card-body">
    {{ include('stagiair/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('stagiair_index') }}" class="btn btn-primary bluebutton"><i class="fas fa-backward"></i></a>

    {{ include('stagiair/_delete_form.html.twig') }}

    </div>
</div>
{% endblock %}

templates/stagiair/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stagiair index{% endblock %}

{% block body %}
    <h1>Stagiair index</h1>

    <table class="table table-striped">
        <thead class="maincolor text-center">
            <tr class="whitetext">
{#                <th>Id</th>#}
{#                <th>Urentotaal</th>#}
                <th>Naam</th>
                <th>Begindatum</th>
                <th>Einddatum</th>
                <th>School</th>
                <th>Contactpersoon</th>
                <th>Emailadres Contactpersoon</th>
                <th>Telefoonnummer Contactpersoon</th>
                {% if is_granted("ROLE_SUPER_ADMIN") %}
                <th></th>
                {% endif %}
            </tr>
        </thead>
        <tbody class="text-center">
        {% for stagiair in stagiairs %}
            <tr>
{#                <td>{{ stagiair.id }}</td>#}
{#                <td>{{ stagiair.urentotaal }}</td>#}
                <td>{{ stagiair.userId }}</td>
                <td>{{ stagiair.begindatum ? stagiair.begindatum|date('Y-m-d') : '' }}</td>
                <td>{{ stagiair.einddatum ? stagiair.einddatum|date('Y-m-d') : '' }}</td>
                <td>{{ stagiair.school }}</td>
                <td>{{ stagiair.contactpersoon }}</td>
                <td>{{ stagiair.contactpersoonEmail }}</td>
                <td>{{ stagiair.contactpersoonTelefoonnr }}</td>
                {% if is_granted("ROLE_SUPER_ADMIN") %}
                <td>
                    <a class="btn btn-success greenbutton mb-2" href="{{ path('stagiair_show', {'id': stagiair.id}) }}"><i class="fas fa-eye"></i></a>
                    <a class="btn btn-warning" href="{{ path('stagiair_edit', {'id': stagiair.id}) }}"><i class="fas fa-edit"></i></a>
                </td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <table class="table table-striped mt-5">
        <thead class="maincolor text-center">
        <tr class="whitetext">
            {#                <th>Id</th>#}
            <th>Uren totaal</th>
            <th>Uren per dag</th>
            <th>Dagen totaal</th>
            <th>Dagen sinds start</th>
            <th>Uren sinds start</th>
            <th>Uren te gaan</th>
            <th>Dagen te gaan</th>
            {% if is_granted("ROLE_SUPER_ADMIN") %}
                <th></th>
            {% endif %}
        </tr>
        </thead>
        <tbody class="text-center">
        {% for stagiair in stagiairs %}

            {% set aantaldagen = stagiair.urentotaal / stagiair.urenperdag %}
            {% set vandaag = "now"|date('Y-m-d') %}

            {% set difference = date(stagiair.begindatum).diff(date(vandaag)) %}
            {% set leftDays = difference.days %}
            {% set leftDaysNoWeekend = leftDays / 7 * 5 %}
            {% set urenSindsStart = leftDaysNoWeekend * stagiair.urenperdag %}
            {% set urenLeft = stagiair.urentotaal - urenSindsStart %}
            {% set dagenLeft = urenLeft / stagiair.urenperdag %}


            <tr>
                <td>{{ stagiair.urentotaal }}</td>
                <td>{{ stagiair.urenperdag }}</td>

                {#<td>{{ stagiair.id }}</td>#}
                {% if stagiair.urenperdag != NULL %}
                <td>{{ aantaldagen }} dagen </td>
                    {% else %}
                    <td>N.V.T</td>
                {% endif %}
                <td>{{ leftDaysNoWeekend|round }}</td>
                <td>{{ urenSindsStart|round }}</td>
                <td>{{ urenLeft|round }}</td>
                <td>{{ dagenLeft|round }}</td>
                {% if is_granted("ROLE_SUPER_ADMIN") %}
                    <td>
                        <a class="btn btn-success greenbutton" href="{{ path('stagiair_show', {'id': stagiair.id}) }}"><i class="fas fa-eye"></i></a>
                        <a class="btn btn-warning" href="{{ path('stagiair_edit', {'id': stagiair.id}) }}"><i class="fas fa-edit"></i></a>
                    </td>
                {% endif %}
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{#    <a href="{{ path('stagiair_new') }}" class="btn btn-success greenbutton">Create new</a>#}
{% endblock %}

templates/stagiair/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Stagiair{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header maincolor whitetext">
        Create new Stagiair    </div>
    <div class="card-body">
    {{ include('stagiair/_form.html.twig') }}

    <a href="{{ path('stagiair_index') }}" class="btn btn-primary bluebutton float-left"><i class="fas fa-backward"></i></a>
    </div>

</div>
{% endblock %}

templates/stagiair/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Stagiair{% endblock %}

{% block body %}
    <table class="table table-striped">
        <thead class="maincolor">
        <tr class="whitetext">
            <th>Stagiair</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
{#            <tr>#}
{#                <th>Id</th>#}
{#                <td>{{ stagiair.id }}</td>#}
{#            </tr>#}
            <tr>
                <th>Urentotaal</th>
                <td>{{ stagiair.urentotaal }}</td>
            </tr>
            <tr>
                <th>Begindatum</th>
                <td>{{ stagiair.begindatum ? stagiair.begindatum|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Einddatum</th>
                <td>{{ stagiair.einddatum ? stagiair.einddatum|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>School</th>
                <td>{{ stagiair.school }}</td>
            </tr>
            <tr>
                <th>Contactpersoon</th>
                <td>{{ stagiair.contactpersoon }}</td>
            </tr>
            <tr>
                <th>Contactpersoon_email</th>
                <td>{{ stagiair.contactpersoonEmail }}</td>
            </tr>
            <tr>
                <th>Contactpersoon_telefoonnr</th>
                <td>{{ stagiair.contactpersoonTelefoonnr }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('stagiair_index') }}" class="btn btn-primary bluebutton"><i class="fas fa-backward"></i></a>

    <a href="{{ path('stagiair_edit', {'id': stagiair.id}) }}" class="btn btn-success greenbutton float-right"><i class="fas fa-edit"></i></a>

    {{ include('stagiair/_delete_form.html.twig') }}
{% endblock %}